name: Dev Branch Push Notification

on:
  push:
    branches:
      - dev

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: 发送 QQ 邮件通知
        uses: dawidd6/action-send-mail@v3
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 
        with:
          server_address: smtp.qq.com
          server_port: 465
          secure: true
          username: 981130406@qq.com
          password: ${{ secrets.QQ_MAIL_KEY }}
          
          # 🌟 这里将邮件标题改为了具体的 commit 消息
          subject: "【dev】${{ github.event.head_commit.message }}"
          
          from: GitHub 机器人 <981130406@qq.com>
          to: 981130406@qq.com,2012209952@qq.com
          body: |
            项目仓库: ${{ github.repository }}
            触发分支: ${{ github.ref_name }}
            代码推送者: ${{ github.actor }}
            
            最新提交信息:
            ${{ github.event.head_commit.message }}
            
            查看本次提交对比详情:
            ${{ github.event.compare }}